from .apis import TykApisApi
from .assets import TykAssetsApi
from .certificates import TykCertificatesApi
from .identity_management_profile import TykIdentityManagementProfilesAPI
from .keys import TykKeysApi
from .policies import TykPoliciesApi
from .usergroups import TykUserGroupsAPI
from .users import TykUsersApi
from .webhooks import TykWebHooksApi